### ISSUE TITLE
Missing ignorekeys keyword

### ISSUE THREAD

**Issue by blueyed** [vimperator/vimperator.vim#2]
`ignorekeys` is not recognized as a command in the syntax file (liberator://help/browsing#%3Aignorekeys).

The list should probably get autogenerated from the Vimperator source?!

**Comment by timss** [comment]
Thanks for reporting that!

Yup, it would definitely be nice if it could be autogenerated. Unfortunately I haven't found an easy way to do it for commands. Maybe some variation of what was done for options in ce672df could be a possible solution.
