### ISSUE TITLE
autocmd JavaScript syntax highlighting

### ISSUE THREAD

**Issue by ropery** [vimperator/vimperator.vim#3]
I request JavaScript syntax support for the following two cases:

```
autocmd DOMLoad .* -js (function(){return true;})();
autocmd DOMLoad .* javascript <<EOF
(function(){
  return true;
})();
EOF
```

(Right now, the here-document syntax is not supported by vimperator, but I made a request vimperator/vimperator-labs#577)

A quick patch that seems to work... but you know better than me :)

```
--- a/syntax/vimperator.vim
+++ b/syntax/vimperator.vim
@@ -74,9 +74,9 @@ syn match vimperatorOption "\<\%(no\|inv\)\=\%(tabnumbers\|tn\|usermode\|um\|vis

 syn match vimperatorSetMod "\%(\<[a-z_]\+\)\@<=&" contained

-syn region vimperatorJavaScript start="\%(^\s*\%(javascript\|js\)\s\+\)\@<=" end="$" contains=@javascriptTop keepend oneline
+syn region vimperatorJavaScript start="\%(^\%(au\%(tocmd\)\s\+.\+\s\+-\?\|\s*\)\%(javascript\|js\)\s\+\)\@<=" end="$" contains=@javascriptTop keepend oneline
 syn region vimperatorJavaScript matchgroup=vimperatorJavascriptDelimiter
-    \ start="\%(^\s*\%(javascript\|js\)\s\+\)\@<=<<\s*\z(\h\w*\)"hs=s+2 end="^\z1$" contains=@javascriptTop fold
+    \ start="\%(^\%(au\%(tocmd\)\s\+.\+\s\+-\?\|\s*\)\%(javascript\|js\)\s\+\)\@<=<<\s*\z(\h\w*\)"hs=s+2 end="^\z1$" contains=@javascriptTop fold

 let s:cssRegionStart = '\%(^\s*sty\%[le]!\=\s\+\%(-\%(n\|name\)\%(\s\+\|=\)\S\+\s\+\)\=[^-]\S\+\s\+\)\@<='
 execute 'syn region vimperatorCss start="' . s:cssRegionStart . '" end="$" contains=@cssTop keepend oneline'
```

**Comment by timss** [comment]
It seems to work for the second `autocmd`, but I can't really see any difference for the first after/before your patch. In fact, I'm not quite sure if javascript syntax highlighting is "correct" in my configuration/vimperator.vim to begin with, haven't thought much about it and I'm not the original author. 

![vimperatorJavaScript](https://i.imgur.com/Q1VdUGf.png)

Does this match your experience? Either way, if this fixes something on your part I'm more than happy to include it. Would you be interested in submitting a PR (after the uncertainties have been resolved)?

**Comment by ropery** [comment]
I think you've just exposed another glitch in this syntax file; if you remove `:` in your `:js` commands, you'll get the correct syntax highlighting.

I don't know why the first line doesn't change the colors for you... I threw the patch together without knowing what everything means on these lines, so... there might be some issues, perhaps performance wise?

**Comment by timss** [comment]
Ah of course, silly error on my part.

I'll have to look into it further later.
