### ISSUE TITLE
request for git tag

### ISSUE THREAD

**Issue by tampakrap** [vimperator/vimperator.vim#6]
I would like to package those files for my distro. Please create a git tag so I can have a proper tarball to install them from

**Comment by timss** [comment]
Thank you for your interest in packaging vimperator.vim! Sounds like a good idea, I'll try to look into proper versioning/tagging when I got some time. 

If you have any suggestions or ideas I'm all ears, or else something simple like 1.0.0 would hopefully work.

**Comment by tampakrap** [comment]
no suggestion from my side, I suppose 1.0.0 should be fine

**Comment by timss** [comment]
Sorry, I kind of forgot about this as I don't tend to fickle with my own Vimperator configuration these days. If it's still of any interest, vimperator.vim's first release is now out:

https://github.com/vimperator/vimperator.vim/releases/tag/v1.0.0
